#!/bin/bash
ps a x u -A | awk '{ printf("%s %s\n",$11,$2) }' | grep "^\/sbin\/" | awk '{ printf("%s\n",$2) }' > sh2.log
ps a x u -A | awk '{ printf("%s %s\n",$12,$2) }' | grep "^\/sbin\/" | awk '{ printf("%s\n",$2) }' >> sh2.log
